services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  DigitalOceanDropletBundle\Command\:
    resource: '../../Command/'
  DigitalOceanDropletBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  DigitalOceanDropletBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  DigitalOceanDropletBundle\Repository\:
    resource: '../../Repository/'
  DigitalOceanDropletBundle\Service\:
    resource: '../../Service/'

  # 菜单服务
  DigitalOceanDropletBundle\Service\AdminMenu:
    tags:
      - { name: tourze.easy_admin_menu.provider }
